# Generated by Django 2.2.4 on 2020-09-01 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0002_auto_20200901_1820'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='basket',
            managers=[
            ],
        ),
    ]
